### ISSUE TITLE
As a user I want to use my own Auth component

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/vue-admin#98]
We should let users use their own custom Auth component.

Notes/Ideas:

+   It should be a prop in **Admin.vue**
+   VueAdmin should provide injected functions as props to:
    +   update the username field
    +   update the password field
    +   submit the form

---

+ [x] Add a custom components to the demo directory
+ [x] ~Implement the necessary helpers expose store functions to login, logout, update user and password fields~ We will leave this for a later issue
+ [x] Refactor the default Auth module to use the va auth helpers
+ [x] Implement the custom Auth component with the injected va object with the auth helper functions
+ [x] ~Implement an e2e test for the custom Auth component~ Let's leave this for another time, since we are not able no implement 2 different auth layouts in a single demo instance
+ [x] Update README.md to with the new feature (take any custom view component documentation as example, written in the same document)

**Comment by sgobotta** [comment]
I've just updated the description with some TODOs. Do they make sense? Is there anything else we should add/remove?

**Comment by sgobotta** [comment]
Removed the e2e test from the TODO list

**Comment by sgobotta** [comment]
Merged in #126
